# Generated by Django 4.2.16 on 2024-09-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('assistant', 'Assistant'), ('staff', 'Staff'), ('customer', 'Customer')], default='customer', max_length=15),
        ),
    ]
